// "Download as Word" engine. Builds rich, branded .docx documents — a running
// header (brand + doc type), a title block, the content, and a footer with a
// note + page numbers. Every download (research dossier, battlecard, proposal
// recommendation, SOW) flows through here so they share one polished layout.

const express = require('express');
const {
  Document, Packer, Paragraph, TextRun, HeadingLevel,
  Header, Footer, PageNumber, BorderStyle, TabStopType, TabStopPosition,
} = require('docx');

const INK = '16181D';
const MUTED = '5B616E';
const LINE = 'E4E7EC';

// Inline markdown → docx TextRuns. Supports **bold**; everything else is plain.
function parseInline(text) {
  const runs = [];
  for (const p of String(text).split(/(\*\*[^*]+\*\*)/g)) {
    if (!p) continue;
    const m = p.match(/^\*\*([^*]+)\*\*$/);
    runs.push(m ? new TextRun({ text: m[1], bold: true }) : new TextRun(p));
  }
  return runs.length ? runs : [new TextRun(String(text))];
}

// Line-based markdown → docx paragraphs. #/##/### headings, - / * bullets,
// **bold**, and plain paragraphs.
function mdToParagraphs(markdown) {
  const out = [];
  for (const raw of String(markdown || '').replace(/\r\n/g, '\n').split('\n')) {
    const line = raw.replace(/\s+$/, '');
    if (!line.trim()) continue;
    if (line.startsWith('### ')) { out.push(new Paragraph({ text: line.slice(4), heading: HeadingLevel.HEADING_3 })); continue; }
    if (line.startsWith('## '))  { out.push(new Paragraph({ text: line.slice(3), heading: HeadingLevel.HEADING_2 })); continue; }
    if (line.startsWith('# '))   { out.push(new Paragraph({ text: line.slice(2), heading: HeadingLevel.HEADING_1 })); continue; }
    const bullet = line.match(/^\s*[-*]\s+(.*)$/);
    if (bullet) { out.push(new Paragraph({ children: parseInline(bullet[1]), bullet: { level: 0 } })); continue; }
    out.push(new Paragraph({ children: parseInline(line), spacing: { after: 120 } }));
  }
  if (!out.length) out.push(new Paragraph({ text: '' }));
  return out;
}

function headerFor(brand, docType) {
  const children = [new TextRun({ text: brand || 'DealScope', bold: true, size: 22, color: INK })];
  if (docType) children.push(new TextRun({ text: '\t' + docType, size: 16, color: MUTED }));
  return new Header({
    children: [new Paragraph({
      tabStops: [{ type: TabStopType.RIGHT, position: TabStopPosition.MAX }],
      border: { bottom: { style: BorderStyle.SINGLE, size: 6, color: LINE, space: 8 } },
      spacing: { after: 240 },
      children,
    })],
  });
}

function footerFor(note) {
  return new Footer({
    children: [new Paragraph({
      tabStops: [{ type: TabStopType.RIGHT, position: TabStopPosition.MAX }],
      border: { top: { style: BorderStyle.SINGLE, size: 6, color: LINE, space: 8 } },
      children: [
        new TextRun({ text: note || 'Generated by DealScope', size: 14, color: MUTED }),
        new TextRun({ children: ['\tPage ', PageNumber.CURRENT, ' of ', PageNumber.TOTAL_PAGES], size: 14, color: MUTED }),
      ],
    })],
  });
}

function titleBlock(title, subtitle) {
  const out = [];
  if (title) out.push(new Paragraph({ spacing: { after: subtitle ? 60 : 260 }, children: [new TextRun({ text: title, bold: true, size: 40, color: INK })] }));
  if (subtitle) out.push(new Paragraph({ spacing: { after: 280 }, children: [new TextRun({ text: subtitle, size: 20, color: MUTED })] }));
  return out;
}

// The one builder everything uses. `paragraphs` is an array of docx Paragraphs.
function buildDocx({ title, subtitle, brand, docType, paragraphs = [], footerNote } = {}) {
  const doc = new Document({
    sections: [{
      headers: { default: headerFor(brand, docType) },
      footers: { default: footerFor(footerNote) },
      children: [...titleBlock(title, subtitle), ...paragraphs],
    }],
  });
  return Packer.toBuffer(doc);
}

// Convenience: rich .docx from a markdown body + layout opts.
function markdownToDocxBuffer(markdown, opts = {}) {
  return buildDocx({ ...opts, paragraphs: mdToParagraphs(markdown) });
}

const router = express.Router();
router.use(express.json({ limit: '1mb' }));

// POST /api/export/docx  { filename, markdown, title?, subtitle?, brand?, docType?, footerNote? }
router.post('/docx', async (req, res) => {
  const b = req.body || {};
  const md = String(b.markdown || '');
  let fn = String(b.filename || 'document.docx').replace(/[^A-Za-z0-9._-]/g, '_').slice(0, 120);
  if (!/\.docx$/i.test(fn)) fn += '.docx';
  if (!md.trim()) return res.status(400).json({ error: 'markdown required' });
  try {
    const buf = await markdownToDocxBuffer(md, {
      title: b.title, subtitle: b.subtitle, brand: b.brand, docType: b.docType, footerNote: b.footerNote,
    });
    res.set('Content-Type', 'application/vnd.openxmlformats-officedocument.wordprocessingml.document');
    res.set('Content-Disposition', `attachment; filename="${fn}"`);
    res.send(buf);
  } catch (err) {
    console.error('[export] docx failed:', (err && err.message) || err);
    res.status(500).json({ error: 'Could not generate the Word document.' });
  }
});

module.exports = { router, buildDocx, markdownToDocxBuffer, mdToParagraphs };
