// The battlecard call site must use — and record — the `battlecard` task's
// model, not `assessment`'s (ADR-0006 §4.1).
//
// providerRouter.test.js proves the ROUTER splits the two keys. That is only
// half the property: a split key that the call site never reads changes
// nothing, and the failure is silent in both directions. `battlecard` resolving
// to Sonnet while extractBattlecard still sends `assessment`'s Haiku id is a
// worse battlecard and no error; the reverse mislabels the persisted
// `model:` field and the `usage_costs` row that ADR-0006 §6's margin table is
// computed from.
//
// So this drives the real function with the two task keys pointed at
// DISTINGUISHABLE models and asserts which one comes out where. The overrides
// must be set before knowledge/assessment.js is required, because it resolves
// both models at require time (see the note at the top of that file).

'use strict';

const path = require('node:path');
const { test } = require('node:test');
const assert = require('node:assert');

const SRC = path.join(__dirname, '..', 'src');

// gemini.js's only eager import is src/redis.js, which constructs a live ioredis
// client at require time with `lazyConnect: false` — that alone keeps the test
// process alive forever after the assertions pass. Faked in require.cache before
// gemini.js loads, exactly as geminiCacheScan.test.js does it. Neither function
// under test touches Redis, so the fake needs no behaviour.
function stubModule(relFromSrc, exportsObj) {
  const full = require.resolve(path.join(SRC, relFromSrc));
  require.cache[full] = { id: full, filename: full, loaded: true, exports: exportsObj };
}
stubModule('redis.js', {});

const ASSESSMENT_PROBE = 'gemini-assessment-probe';
const BATTLECARD_PROBE = 'gemini-battlecard-probe';
process.env.GEMINI_ASSESSMENT_MODEL = ASSESSMENT_PROBE;
process.env.GEMINI_BATTLECARD_MODEL = BATTLECARD_PROBE;

const db = require(path.join(SRC, 'db.js'));
const gemini = require(path.join(SRC, 'gemini.js'));
const costs = require(path.join(SRC, 'costs.js'));
const keypoints = require(path.join(SRC, 'knowledge', 'keypoints.js'));

// Required LAST so the two env overrides above are in force when its
// module-scope modelFor() calls run.
const assessment = require(path.join(SRC, 'knowledge', 'assessment.js'));

// The generation calls the two entry points make, in order.
const calls = [];
const recorded = [];

gemini.getClient = () => ({
  models: {
    generateContent: async (req) => {
      calls.push({ model: req.model, maxOutputTokens: req.config.maxOutputTokens });
      return {
        text: JSON.stringify({
          // BATTLECARD_SCHEMA's required fields …
          verdictHeadline: 'They win on ecosystem; we win on price.',
          whereWeWin: [], whereWeLose: [], talkTrack: [], objections: [],
          // … and ASSESSMENT_SCHEMA's.
          summary: 'They lead on integrations.',
          axes: [], topImprovements: [],
        }),
        usageMetadata: { promptTokenCount: 10, candidatesTokenCount: 5 },
      };
    },
  },
});
costs.recordGemini = (tenantId, site, model) => { recorded.push({ site, model }); };
keypoints.tenantContextText = async () => 'our context';

// extractBattlecard issues three queries in a fixed order; dispatch on the
// table each one names rather than on call count, so an added query does not
// silently shift the fixtures onto the wrong statement.
db.query = async (sql) => {
  if (/FROM competitors/.test(sql)) return { rows: [{ name: 'Acme' }] };
  if (/kb_document_competitors/.test(sql)) {
    return { rows: [{ id: 'doc_1', title: 'Acme dossier', metadata: {}, body: 'Acme ships an API marketplace. '.repeat(40) }] };
  }
  if (/kb_documents/.test(sql)) {
    return { rows: [{ id: 'doc_2', title: 'Our portfolio', body: 'We ship a fraud engine. '.repeat(40), product_ids: null }] };
  }
  throw new Error(`unexpected query in test: ${String(sql).slice(0, 80)}`);
};

test('the battlecard synthesis sends, records and stamps the battlecard model', async () => {
  calls.length = 0; recorded.length = 0;

  const card = await assessment.extractBattlecard('ten_1', 'cmp_1');

  assert.strictEqual(calls.length, 1);
  assert.strictEqual(calls[0].model, BATTLECARD_PROBE,
    'the synthesis must be generated by the battlecard task, not by the per-document scorer');
  assert.deepStrictEqual(recorded, [{ site: 'kb.battlecard', model: BATTLECARD_PROBE }],
    'usage_costs is what ADR-0006 §6 is re-computed from — a mislabelled model prices the wrong tier');
  assert.strictEqual(card.model, BATTLECARD_PROBE,
    'competitors.battlecard.model is persisted; it must name the model that produced THIS card');
});

test('the per-document scorer keeps the assessment model', async () => {
  calls.length = 0; recorded.length = 0;

  const scored = await assessment.extractCompetitiveAssessment({
    text: 'Acme ships an API marketplace and a partner network. '.repeat(10),
    tenantId: 'ten_1',
    competitorName: 'Acme',
  });

  assert.ok(scored, 'extractCompetitiveAssessment swallows its own errors — a null here means it never got to the model');
  assert.strictEqual(calls.length, 1);
  assert.strictEqual(calls[0].model, ASSESSMENT_PROBE,
    'only the battlecard half moves; splitting the key must not re-point the scorer');
  assert.deepStrictEqual(recorded, [{ site: 'kb.assessment', model: ASSESSMENT_PROBE }]);
});
